import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/ui/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-linear-to-r/srgb from-gray-900 from-5% via-gray-700 via-50% to-gray-900 to-95%`}
      >
        <Providers>
          <div className="min-h-screen">
            <Navbar />
            <main className="container mx-auto px-4">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
